language: cpp
compiler: gcc
sudo: true
cache:
  - apt
#addons:
 #apt:
   #sources:
   #- ubuntu-toolchain-r-test
   #- ubuntu-sdk-team
   #- beineri/opt-qt521
   #packages:
   #- cmake
   #- gcc-4.8
   #- g++-4.8
   #- qt52base
   #- qt52-meta
   #- qtbase5-dev
   #- qt5-default
   #- qttools5-dev-tools
before_script:
  - sudo apt-add-repository ppa:beineri/opt-qt521 -y
  - sudo apt-add-repository ppa:ubuntu-toolchain-r-test/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install cmake gcc-4.8 g++-4.8 qt52base qt52-meta qt52tools -y
  - export CXX=g++-4.8 CC=gcc-4.8
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DPR_ONLY_LIBRARY_SUBS=ON -DPM_ONLY_LIBRARY=ON -DPP_ONLY_LIBRARY=ON -DDL_ONLY_LIBRARY=ON ..
script:
  - make
  - bin/pr_test_boundingbox
  - bin/pr_test_brdf
  - bin/pr_test_entity
  - bin/pr_test_plane
  - bin/pr_test_projection
  - bin/pr_test_spectrum
  - bin/pr_test_sphere

branches:
  only:
  - master
notifications:
  email: false
