language: cpp
dist: bionic
addons:
  apt:
    update: true
    packages:
      - lcov
      - qtbase5-dev
      - libqt5charts5-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libeigen3-dev
      - libopenexr-dev
      - libtbb-dev
      - libopenimageio-dev
      - python3.6-dev
      - python3.6-venv
      - python3-numpy
      - python2.7-dev
      - python-virtualenv
      - python-numpy
      - ninja-build
cache: ccache
env:
  global:
    - CXXFLAGS="-Wall -Wextra -march=native"
jobs:
  fast_finish: true
  include:
    - compiler: gcc
      env: USE_COVERAGE=ON PYTHON=3.6 EMBED_PLUGINS=OFF
    - compiler: gcc
      env: USE_COVERAGE=OFF PYTHON=3.6 EMBED_PLUGINS=ON
    - compiler: gcc
      env: USE_COVERAGE=OFF PYTHON=2.7 EMBED_PLUGINS=OFF
    - compiler: clang
      env: USE_COVERAGE=OFF PYTHON=3.6 EMBED_PLUGINS=OFF
    - compiler: clang
      env: USE_COVERAGE=OFF PYTHON=3.6 EMBED_PLUGINS=ON
    - compiler: clang
      env: USE_COVERAGE=OFF PYTHON=2.7 EMBED_PLUGINS=OFF
before_script:
  - $CXX --version
  - cmake --version
  - wget https://github.com/embree/embree/releases/download/v3.10.0/embree-3.10.0.x86_64.linux.tar.gz
  - mkdir -p embree3
  - tar -xf embree-3.10.0.x86_64.linux.tar.gz -C embree3
  - mkdir build
  - cd build
  - if [ $USE_COVERAGE == ON ]; then lcov --directory . --zerocounters; fi
  - cmake -G "Ninja" -DEmbree_DIR="embree3/" -DCMAKE_BUILD_TYPE=Debug -DPR_USE_LTO=OFF -DPR_GENERATE_COVERAGE=$USE_COVERAGE -DPYBIND11_PYTHON_VERSION=$PYTHON -DPR_EMBED_PLUGINS=$EMBED_PLUGINS ..
script:
  - ninja
after_success:
  - ctest --output-on-failure
  - if [ $USE_COVERAGE == ON ]; then ninja coveralls; fi
notifications:
  email: false
