language: cpp
compiler: gcc
sudo: true
env:
  global:
    - MAKEFLAGS="-j 2"
cache:
  - apt
before_install:
#  - sudo -E apt-add-repository -y "ppa:beineri/opt-qt521"
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo -E apt-add-repository -y "ppa:boost-latest/ppa"
  - sudo -E apt-add-repository -y "ppa:george-edison55/precise-backports"
  - sudo -E apt-get update -qq
install:
# Coverage
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install lcov 
  - pip install --user cpp-coveralls
# CMake and GCC
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install cmake cmake-data gcc-4.8 g++-4.8 
  - export CXX=g++-4.8 CC=gcc-4.8
# Qt
#  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install qt52base qt52tools 
# Boost
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-system1.55-dev libboost-iostreams1.55-dev libboost-thread1.55-dev
# OpenEXR
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libopenexr-dev libilmbase-dev
# Intel TBB
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libtbb-dev
# Eigen3
  - wget http://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz -O /tmp/eigen-3.3.3.tar.gz
  - tar zxf /tmp/eigen-3.3.3.tar.gz > /dev/null 2>&1
  - cd eigen-eigen-67e894c6cd8f
  - mkdir build
  - cd build
  - cmake ../
  - sudo make install
  - cd ../../
# OpenImageIO
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libopenjpeg-dev libtiff-dev libjpeg-dev libpng-dev
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.6.11.tar.gz -O /tmp/OpenImageIO-1.6.11.tar.gz
  - tar zxf /tmp/OpenImageIO-1.6.11.tar.gz > /dev/null 2>&1
  - cd oiio-Release-1.6.11
  - mkdir build
  - cd build
  - cmake -DUSE_QT=0 -DUSE_TBB=0 -DUSE_PYTHON=0 -DUSE_PYTHON3=0 -DUSE_FIELD3D=0 -DUSE_FFMPEG=0 -DUSE_OPENJPEG=1 -DUSE_OCIO=0 -DUSE_OPENCV=0 -DUSE_OPENSSL=0 -DUSE_FREETYPE=0 -DUSE_GIF=0 -DUSE_PTEX=0 -DUSE_LIBRAW=0 -DOIIO_BUILD_TESTS=0 -DOIIO_BUILD_TOOLS=0 ../
  - make $MAKEFLAGS 
  - sudo make install
  - cd ../../
before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - lcov --directory . --zerocounters
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPR_ONLY_LIBRARY_SUBS=ON -DDL_ONLY_LIBRARY=ON -DPR_GENERATE_COVERAGE=ON ..
script:
  - make $MAKEFLAGS 
  - make test || true
after_success:
  - lcov --capture --no-external --directory . --output-file coverage.info --base-directory ../src/
  - coveralls -r ../ -b . --exclude sandbox --exclude datalisp --exclude viewer --exclude tests --repo-token ${COVERALLS_TOKEN} --gcov-options '\-lp'
branches:
  only:
  - master
notifications:
  email: false
