language: cpp
compiler:
  gcc
  clang
dist: bionic
sudo: true
cache:
  - apt
addons:
  apt:
    update: true
before_install:
  - sudo apt-get -y install lcov qtbase5-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-iostreams-dev libboost-thread-dev libopenexr-dev libtbb-dev libeigen3-dev libopenimageio-dev
install:
before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - lcov --directory . --zerocounters
  - cmake -E env CXXFLAGS="-O0" cmake -DCMAKE_BUILD_TYPE=Debug -DPYBIND11_PYTHON_VERSION="3.7" ..
script:
  - make $MAKEFLAGS
  - make test || true
  - make coveralls
branches:
  only:
  - master
notifications:
  email: false
