language: cpp
dist: bionic
addons:
  apt:
    update: true
    packages:
      - lcov
      - qtbase5-dev
      - libqt5charts5-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libeigen3-dev
      - libopenexr-dev
      - libtbb-dev
      - libopenimageio-dev
      - python3.6-dev
      - python3.6-venv
      - python3-numpy
      - python2.7-dev
      - python-virtualenv
      - python-numpy
cache: ccache
env:
  global:
    - MAKE_FLAGS=-j4
    - CXXFLAGS="-Wall -Wextra -march=native"
jobs:
  fast_finish: true
  include:
    - compiler: gcc
      env: USE_COVERAGE=ON PYTHON=3.6
    - compiler: gcc
      env: USE_COVERAGE=OFF PYTHON=2.7
    - compiler: clang
      env: USE_COVERAGE=OFF PYTHON=3.6
before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - if [ $USE_COVERAGE == ON ]; then lcov --directory . --zerocounters; fi
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPR_USE_LTO=OFF -DPR_USE_LTO_ONLY_RELEASE=ON -DPR_GENERATE_COVERAGE=$USE_COVERAGE -DPYBIND11_PYTHON_VERSION=$PYTHON ..
script:
  - make $MAKE_FLAGS
after_success:
  - ctest --output-on-failure
  - if [ $USE_COVERAGE == ON ]; then make coveralls; fi
notifications:
  email: false
