language: cpp
compiler:
  gcc
  clang
dist: bionic
env:
  global:
    - PYTHON=3.6
    - MAKE_FLAGS=-j4
    - CXXFLAGS="-Wall -Wextra -march=native"
addons:
  apt:
    update: true
    packages:
      - lcov
      - qtbase5-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libeigen3-dev
      - libopenexr-dev
      - libtbb-dev
      - libopenimageio-dev
      - python3.6-dev
      - python3.6-venv
before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - lcov --directory . --zerocounters
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPYBIND11_PYTHON_VERSION=$PYTHON ..
script:
  - make $MAKE_FLAGS
  - make test || true
  - make coveralls
branches:
  only:
  - master
notifications:
  email: false
