def export(filename, p, n, st, inds):
    with open(filename, "w") as output:
        output.write("# obj file for pearray - Generated by pbrt2prc\n")

        for i in range(int(len(p)/3)):
            output.write("v %s %s %s\n" %
                         (str(p[i*3]), str(p[i*3+1]), str(p[i*3+2])))

        for i in range(int(len(n)/3)):
            output.write("vn %s %s %s\n" %
                         (str(n[i*3]), str(n[i*3+1]), str(n[i*3+2])))

        for i in range(int(len(st)/2)):
            output.write("vt %s %s\n" % (str(st[i*2]), str(st[i*2+1])))

        for i in range(int(len(inds)/3)):
            output.write("f %s %s %s\n" % (
                str(inds[i*3]+1), str(inds[i*3+1]+1), str(inds[i*3+2]+1)))
