#!/usr/bin/python
# -*- coding: utf-8 -*-

# Use:
# cos_hemi.py CVS

import sys
import math
import numpy as np
import matplotlib.pyplot as plt

if __name__=='__main__':
    if len(sys.argv) != 2:
        print("Not enough arguments given. Need an cvs generated by 'pr_sandbox projection1'")
        exit()

    M = np.loadtxt(sys.argv[1])
    Entries = int(math.sqrt(M.shape[0]))# Should be square... but we do not check
    Plots = M.shape[1]-2
    T = np.zeros([Entries,Entries])

    n1 = int(math.ceil(math.sqrt(Plots)))
    fig = plt.figure()
    for i in range(2,Plots+2):
        ax = fig.add_subplot(n1,n1,i-1)
        for j in range(0,Entries):
            for k in range(0,Entries):
                T[j,k] = M[j*Entries+k,i]
        ax.imshow(T, interpolation='nearest')
        ax.axis('off')
    
    plt.tight_layout()
    plt.savefig("output.png", bbox_inches='tight')
