file(GLOB_RECURSE HDR_FILES_BASE "src/base/*.h")
file(GLOB_RECURSE HDR_FILES_CORE "src/core/*.h")
file(GLOB_RECURSE HDR_FILES_LOADER "src/loader/*.h")
file(GLOB_RECURSE HDR_FILES_PYTHON "src/python/*.h")
set(HDR_FILES ${HDR_FILES_BASE} ${HDR_FILES_CORE} ${HDR_FILES_LOADER} ${HDR_FILES_PYTHON})

file(GLOB_RECURSE HDR_IN_FILES_BASE "src/base/*.inl")
file(GLOB_RECURSE HDR_IN_FILES_CORE "src/core/*.inl")
file(GLOB_RECURSE HDR_IN_FILES_LOADER "src/loader/*.inl")
file(GLOB_RECURSE HDR_IN_FILES_PYTHON "src/python/*.inl")
set(HDR_IN_FILES ${HDR_IN_FILES_BASE} ${HDR_IN_FILES_CORE} ${HDR_IN_FILES_LOADER} ${HDR_IN_FILES_PYTHON})

file(GLOB_RECURSE SRC_FILES_BASE "src/base/*.cpp")
file(GLOB_RECURSE SRC_FILES_CORE "src/core/*.cpp")
file(GLOB_RECURSE SRC_FILES_LOADER "src/loader/*.cpp")
file(GLOB_RECURSE SRC_FILES_PYTHON "src/python/*.cpp")
set(SRC_FILES ${SRC_FILES_BASE} ${SRC_FILES_CORE} ${SRC_FILES_LOADER} ${SRC_FILES_PYTHON})

SET(CV_FILES ${HDR_FILES} ${HDR_IN_FILES} ${SRC_FILES})

coveralls_setup("${CV_FILES}" ON)