# Locate OpenEXR
# This module defines
#  OPENEXR_FOUND, if false, do not try to link to OSL
#  OPENEXR_LIBRARIES
#  OPENEXR_INCLUDE_DIR
#
# Calling convection: <OpenEXR/version.h>

SET(OPENEXR_FOUND FALSE)
SET(OPENEXR_INCLUDE_DIRS)
SET(OPENEXR_LIBRARIES)

SET(_Paths ~/Library/Frameworks
  /Library/Frameworks
  /sw
  /opt/local
  /opt/csw
  /opt
  /usr
  ${CMAKE_LIBRARY_PATH}
  ${OPENEXR_DIR})
  
function(OPENEXR_FIND_LIB setname names)
find_library(${setname}
  NAMES ${names}
  HINTS
    ENV OPENEXR_HOME
  PATH_SUFFIXES lib
  PATHS ${_Paths}
)
endfunction()

find_path(OPENEXR_INCLUDE_DIR OpenEXR/ImfVersion.h
  HINTS
    ENV OPENEXR_HOME
  PATH_SUFFIXES include local/include 
  PATHS ${_Paths}
)
IF(OPENEXR_INCLUDE_DIR)
	SET(OPENEXR_INCLUDE_DIRS ${OPENEXR_INCLUDE_DIR})
ENDIF()

OPENEXR_FIND_LIB(OPENEXR_LIBRARY_HALF Half)
OPENEXR_FIND_LIB(OPENEXR_LIBRARY_IEX Iex)
OPENEXR_FIND_LIB(OPENEXR_LIBRARY_IMATH Imath)
OPENEXR_FIND_LIB(OPENEXR_LIBRARY_ILMIMF IlmImf)
OPENEXR_FIND_LIB(OPENEXR_LIBRARY_ILMTHREAD IlmThread)

IF(OPENEXR_LIBRARY_HALF AND OPENEXR_LIBRARY_IEX AND OPENEXR_LIBRARY_IMATH AND OPENEXR_LIBRARY_ILMIMF AND OPENEXR_LIBRARY_ILMTHREAD)
	SET(OPENEXR_LIBRARIES ${OPENEXR_LIBRARY_HALF} ${OPENEXR_LIBRARY_IEX}
	${OPENEXR_LIBRARY_IMATH} ${OPENEXR_LIBRARY_ILMIMF} ${OPENEXR_LIBRARY_ILMTHREAD} )
ENDIF()

IF (OPENEXR_INCLUDE_DIR AND OPENEXR_LIBRARIES)
	SET(OPENEXR_FOUND TRUE)
ENDIF()

IF (OPENEXR_FOUND)
	IF (NOT OPENEXR_FIND_QUIETLY)
		MESSAGE(STATUS "Found OpenEXR: ${OPENEXR_INCLUDE_DIR} LIBS: ${OPENEXR_LIBRARIES}")
	ENDIF (NOT OPENEXR_FIND_QUIETLY)
ELSE ()
	IF (OPENEXR_FIND_QUIETLY)
		MESSAGE(FATAL_ERROR "Could not find OpenEXR")
	ENDIF (OPENEXR_FIND_QUIETLY)
ENDIF ()

mark_as_advanced(OPENEXR_INCLUDE_DIR
 OPENEXR_LIBRARY_HALF OPENEXR_LIBRARY_IEX OPENEXR_LIBRARY_IMATH OPENEXR_LIBRARY_ILMIMF OPENEXR_LIBRARY_ILMTHREAD)

