# Locate Free Image
# This module defines
#  FREEIMAGE_FOUND, if false, do not try to link to FreeImage
#  FREEIMAGE_LIBRARIY
#  FREEIMAGE_INCLUDE_DIR
#
# Note that the expected include convention is
#  #include <FreeImage.h>

SET(FREEIMAGE_FOUND FALSE)
SET(FREEIMAGE_INCLUDE_DIRS)
SET(FREEIMAGE_LIBRARIES)

find_path(FREEIMAGE_INCLUDE_DIR FreeImage.h
  HINTS
    ENV FREEIMAGE_DIR
  PATH_SUFFIXES include/FreeImage include local/include local/include/FreeImage
  PATHS
  ~/Library/Frameworks
  /Library/Frameworks
  /sw # Fink
  /opt/csw # Blastwave
  /opt
  /usr
  ${CMAKE_LIBRARY_PATH}
)
IF(FREEIMAGE_INCLUDE_DIR)
	SET(FREEIMAGE_INCLUDE_DIRS ${FREEIMAGE_INCLUDE_DIR})
ENDIF()

find_library(FREEIMAGE_LIBRARY
  NAMES freeimage
  HINTS
    ENV FREEIMAGE_DIR
  PATH_SUFFIXES lib
  PATHS
  ~/Library/Frameworks
  /Library/Frameworks
  /sw
  /opt/local
  /opt/csw
  /opt
  /usr
  ${CMAKE_LIBRARY_PATH}
)
IF(FREEIMAGE_LIBRARY)
	SET(FREEIMAGE_LIBRARIES ${FREEIMAGE_LIBRARY})
ENDIF()

IF (FREEIMAGE_DIR AND FREEIMAGE_LIBRARY)
	SET(FREEIMAGE_FOUND TRUE)
ENDIF()

IF (FREEIMAGE_FOUND)
	IF (NOT FREEIMAGE_FIND_QUIETLY)
		MESSAGE(STATUS "  Found FreeImage : ${FREEIMAGE_LIBRARIES}")
	ENDIF (NOT FREEIMAGE_FIND_QUIETLY)
ELSE (FREEIMAGE_FOUND)
	IF (FREEIMAGE_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find FreeImage")
	ENDIF (FREEIMAGE_FIND_REQUIRED)
ENDIF (FREEIMAGE_FOUND)

mark_as_advanced(FREEIMAGE_INCLUDE_DIR FREEIMAGE_LIBRARY FREEIMAGE_INCLUDE_DIRS FREEIMAGE_LIBRARIES)

