if(CMAKE_VERSION VERSION_GREATER 3.9)
    if(PR_USE_LTO)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT supported OUTPUT error)
        if( supported )
            message(STATUS "IPO / LTO enabled")
            set(LTO_ON TRUE)
        else()
            message(WARNING "IPO / LTO not available")
        endif()
    endif()
endif()

function(add_lto TARGET)
    if(LTO_ON)
        if(PR_USE_LTO_ONLY_RELEASE)
            set_property(TARGET ${TARGET}
                    PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
        else()
            set_property(TARGET ${TARGET}
                    PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
        endif()
    endif()
endfunction()